name: 'Github Actions Weather Bot'

on:
  push:
  schedule:
    - cron: '0 7 * * *'

jobs:
  bot:
    runs-on: ubuntu-latest
    steps:
      - name: 'Checkout Repository when Running'
        uses: actions/checkout@v1
      - name: 'Install Node'
        uses: actions/setup-node@v1
      - name: 'Install Project Dependencies'
        run: npm install
      - name: 'Run Bot'
        run: node index.js
        env:
          TELEGRAM_CHAT_ID = ${{ secrets.TELEGRAM_CHAT_ID }}
          TELEGRAM_TOKEN = ${{ secrets.TELEGRAM_TOKEN }}
          WEATHER_API_TOKEN = ${{ secrets.WEATHER_API_TOKEN  }}
